# Generated by Django 3.2.14 on 2022-08-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('created_at',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
    ]
