# Generated by Django 3.2.14 on 2022-08-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tours_amount'),
        ('applications', '0002_auto_20220812_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное имя пользователя'),
        ),
        migrations.AddField(
            model_name='application',
            name='pay_url',
            field=models.URLField(default='1', verbose_name='Ссылка на оплату'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('pg_salt', models.CharField(max_length=255, verbose_name='Ключевое слово')),
                ('pg_sig', models.CharField(max_length=255, verbose_name='Подпись')),
                ('status', models.IntegerField(choices=[(0, 'УСПЕШНО'), (1, 'ОШИБКА')], default=0, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tours')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
