# Generated by Django 3.2.14 on 2022-08-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20220804_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourbanner',
            options={'verbose_name': 'Баннер тура', 'verbose_name_plural': 'Баннеры тура'},
        ),
        migrations.AddField(
            model_name='tours',
            name='city',
            field=models.CharField(default='EA', max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
