# Generated by Django 3.2.14 on 2022-08-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20220804_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='main_image',
            field=models.ImageField(default='1', upload_to='tours', verbose_name='Основное изображение'),
            preserve_default=False,
        ),
    ]
