# Generated by Django 3.2.14 on 2022-08-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tourshots_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
    ]
