# Generated by Django 3.2.14 on 2022-08-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tours_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='currency',
            field=models.IntegerField(choices=[(0, 'UZS'), (1, 'USD'), (2, 'EUR')], default=0, verbose_name='Курс'),
        ),
    ]
