# Generated by Django 3.2.14 on 2022-08-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tours_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToursFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Условие', max_length=200, verbose_name='Название условии')),
                ('means', models.CharField(default='Значение', max_length=200, verbose_name='Значение')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tours.tours', verbose_name='Условия тура')),
            ],
        ),
    ]
