# Generated by Django 3.2.14 on 2022-08-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_toursfeatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toursfeatures',
            options={'verbose_name': 'Условие тура', 'verbose_name_plural': 'Условии тура'},
        ),
    ]
