# Generated by Django 3.2.14 on 2022-08-18 08:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_toursfeatures_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание'),
        ),
    ]
